In [1]:
import numpy as np

In [2]:
tmp = np.zeros(3)
A = np.zeros((3, 3))

In [3]:
tmp[1] = 1
tmp, A

(array([0., 1., 0.]),
 array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]))

In [4]:
A[0] = tmp
tmp, A

(array([0., 1., 0.]),
 array([[0., 1., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]))

In [5]:
tmp[0] = 999
tmp, A

(array([999.,   1.,   0.]),
 array([[0., 1., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]))

In [6]:
A[1] = tmp
tmp, A

(array([999.,   1.,   0.]),
 array([[  0.,   1.,   0.],
        [999.,   1.,   0.],
        [  0.,   0.,   0.]]))

In [7]:
tmp[2] = -4
A[2] = tmp
tmp, A

(array([999.,   1.,  -4.]),
 array([[  0.,   1.,   0.],
        [999.,   1.,   0.],
        [999.,   1.,  -4.]]))

In [8]:
def f(x):
    return np.argsort(x)#[::-1]

In [9]:
import random
x = np.array([i for i in range(0, 500)])
random.shuffle(x)
print(x)
# y = range(1, 9)
# Ordery = np.argsort(y)[::-1]
Orderx = f(x)
print(Orderx)
print(f(Orderx))

all( x == f(f(f(f(x)))) ), all( x == f(f(f(x))) ), all( x == f(f(x)) )

[216  23 477  41 414  83 370 397 250 344 131  14 221 438 454 159 102 440
 184 268 144  20 425  54 398 423  95 395 160 392   3 125 223 247 498 488
 375 480 340 147 473  10  44   5  86 311 151 390 292 179 441 446 387 175
 497  38 206 106 140 313 354 469 189 120 373 433 282 220 137 141 405  88
 450 240 459 103 255  22 193 148 472 435 345 426  61 407 259 314 161 365
 346 210 114 207  87 490 404 181 284  91 456 409 499 182 116 227 393 258
 263  59  57 113 253 232  32 130 349 293 277 105 124 432 316 466 196 218
  36 315 266 367 372 136 399 265 312 121 262 389 391 233 245 297 324  55
 149 288  39 302 177 301 481 305  48  73 452 187  89 485 115 424 379 486
  29 109 185 156 244 236 254 228 117 350 451 385 163 448 378 261  52 174
 122 145 363 420 176 411 323   8 127  82 476 419  81 351 256 195 243 183
  92 111 406  11 276 380 296 475 146  77 289 491 134 403 325  80 219 439
 190 172 201  31 238 443 237 360  75 374 215  97 421 197 203 107 437 167
 110 278 478  51 208  74 327 173 322 468 198 251   

(True, False, True)

In [81]:
# print(np.array(x))
print(Orderx)
tmp = Orderx
for i in range(10):
    tmp = f(tmp)
    print(tmp)

[29 22 10 30 20 35 19  4  2 31 45 12 48 42 14 16 26  7 24 23 39 27 49 36
 40 44  6 17 18 37 41 43 47 15  0 34 21 28 46  9 38  5 32 13 11 25  1 33
  8  3]
[22 12 32 38 10 25 31 13 30 24 20 40 29 23  5 35 47 42  9  3  0 37 21 16
 45 18 19  1 36  4  6 28 27 15 33 14 43 11 44  2 39 48 17 26 41  7 49  8
 46 34]
[46 41 16 48 24 38 36 17 44 11 40  3 21 28 15 49 34  2  6  8 12 31 32 43
  5  9 13  0 22 10 26 25 42 23 33 35  7  1 37  4 18 47 45 30 14 29 19 39
 27 20]
[15  3 41  0 42  8 23 32  1 10 47  5 38  6 35 16 34 22 21 43 45 13 48 30
 31  4 33 28 12 49 46 40  7  2 14 44 26 20  9 29 25 19 36 18 24 39 11 17
 37 27]
[29 22 10 30 20 35 19  4  2 31 45 12 48 42 14 16 26  7 24 23 39 27 49 36
 40 44  6 17 18 37 41 43 47 15  0 34 21 28 46  9 38  5 32 13 11 25  1 33
  8  3]
[22 12 32 38 10 25 31 13 30 24 20 40 29 23  5 35 47 42  9  3  0 37 21 16
 45 18 19  1 36  4  6 28 27 15 33 14 43 11 44  2 39 48 17 26 41  7 49  8
 46 34]
[46 41 16 48 24 38 36 17 44 11 40  3 21 28 15 49 34  2  6  8 12 31 32 43
  5