In [3]:
import numpy as np
import random

In [4]:
test_size = None
if test_size is None:
    test_size = 1
    print(1)
np.log(2.7)

1


0.9932517730102834

In [6]:
x = np.loadtxt('test2.txt')
print(type(x), x)
np.log(10)

<class 'numpy.ndarray'> 114514.0


2.302585092994046

In [58]:
x = np.loadtxt('test1.txt', ndmin = 1).tolist()
y = np.loadtxt('test1.txt', ndmin = 1)
# try:
#     dist_size = len(x)
# except Exception as e:
#     print(e)
#     x = [float(x)]
#     dist_size = 1
# x = list(x)
# x + y
print(x, type(x))

[2.0, 3.0] <class 'list'>


In [40]:
x = np.loadtxt('test3.txt')
x

C:\Users\lx\AppData\Local\Temp\ipykernel_27224\4253042485.py:1: UserWarning: loadtxt: input contained no data: "test3.txt"
  x = np.loadtxt('test3.txt')


array([], dtype=float64)

In [41]:
x + [1,2]

ValueError: operands could not be broadcast together with shapes (0,) (2,) 

In [4]:
np.savetxt('test2.txt', [2,3])

In [1]:
np.savetxt('test.txt', [1,2,3])
newx = [114514, 1919810]
with open('test.txt', 'a') as f:
    f.writelines([str(num) + '\n' for num in newx])

NameError: name 'np' is not defined

In [5]:
rng = np.random.RandomState(100)

In [47]:
rng.randint(0, 100)

71

In [2]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
N = 5

In [8]:
# A : random lower-triangle matrix
A = np.array([[np.random.rand() if i > j else (1 if i == j else 0) for j in range(N)] for i in range(N)])
# X : pd, covariance
X = np.dot(A, A.transpose())
# Sig : marginal variance
Sig = [X[i][i] for i in range(N)]
# X : cov to corr
X = np.array([[X[i][j] / np.sqrt(Sig[i] * Sig[j]) for j in range(N)] for i in range(N)]) 
print(X)

[[1.         0.39912543 0.16992318 0.38022614 0.5402031 ]
 [0.39912543 1.         0.1657336  0.63841033 0.67553339]
 [0.16992318 0.1657336  1.         0.46583856 0.21071163]
 [0.38022614 0.63841033 0.46583856 1.         0.53525577]
 [0.5402031  0.67553339 0.21071163 0.53525577 1.        ]]


In [16]:
rowSort = np.zeros((N, N))
for i in range(N):
    Order = np.argsort(X[i])[::-1] # Order[k] = j: X[i][j]在第i行是第k大
    for k in range(N):
        rowSort[i][Order[k]] = k+1

In [17]:
rowSort

array([[1., 3., 5., 4., 2.],
       [4., 1., 5., 3., 2.],
       [4., 5., 1., 2., 3.],
       [5., 2., 4., 1., 3.],
       [3., 2., 5., 4., 1.]])

In [14]:
rowSort[1, 2]

4.0

In [18]:
def f():
    if 1:
        print('aaa')
        return
    print(2)

In [19]:
f()

aaa


In [20]:
import warnings

In [21]:
warnings.warn('a')

C:\Users\lx\AppData\Local\Temp\ipykernel_11920\1121297883.py:1: UserWarning: a
  warnings.warn('a')
