In [1]:
import numpy as np

In [2]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
N = 5

In [8]:
# A : random lower-triangle matrix
A = np.array([[np.random.rand() if i > j else (1 if i == j else 0) for j in range(N)] for i in range(N)])
# X : pd, covariance
X = np.dot(A, A.transpose())
# Sig : marginal variance
Sig = [X[i][i] for i in range(N)]
# X : cov to corr
X = np.array([[X[i][j] / np.sqrt(Sig[i] * Sig[j]) for j in range(N)] for i in range(N)]) 
print(X)

[[1.         0.39912543 0.16992318 0.38022614 0.5402031 ]
 [0.39912543 1.         0.1657336  0.63841033 0.67553339]
 [0.16992318 0.1657336  1.         0.46583856 0.21071163]
 [0.38022614 0.63841033 0.46583856 1.         0.53525577]
 [0.5402031  0.67553339 0.21071163 0.53525577 1.        ]]


In [16]:
rowSort = np.zeros((N, N))
for i in range(N):
    Order = np.argsort(X[i])[::-1] # Order[k] = j: X[i][j]在第i行是第k大
    for k in range(N):
        rowSort[i][Order[k]] = k+1

In [17]:
rowSort

array([[1., 3., 5., 4., 2.],
       [4., 1., 5., 3., 2.],
       [4., 5., 1., 2., 3.],
       [5., 2., 4., 1., 3.],
       [3., 2., 5., 4., 1.]])

In [14]:
rowSort[1, 2]

4.0

In [18]:
def f():
    if 1:
        print('aaa')
        return
    print(2)

In [19]:
f()

aaa


In [20]:
import warnings

In [21]:
warnings.warn('a')

C:\Users\lx\AppData\Local\Temp\ipykernel_11920\1121297883.py:1: UserWarning: a
  warnings.warn('a')
